version: "3"

services:
  app:
    build:
      context: .
      args:
        - UNAME=${USER}
        - UID=1000
        - GID=1000
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/${UID}/gdm/Xauthority:/home/${USER}/.Xauthority
      - ${HOME}/.config/nymea:/home/${USER}/.config/nymea
    network_mode: host
    hostname: ${HOSTNAME}
